#!/bin/sh
set -e

# Configure mail on boot
echo "configuring ssmtp"
envsubst < /ssmtp.conf.tpl > /etc/ssmtp/ssmtp.conf

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
